INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Turks and Caicos Islands');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Grenada');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Namibia');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Malaysia');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Pitcairn Islands');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Lithuania');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Canada');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Equatorial Guinea');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Qatar');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Turkey');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Trinidad and Tobago');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Reunion');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Svalbard and Jan Mayen Islands');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Mayotte');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Guinea');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Suriname');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Equatorial Guinea');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Belize');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Dominica');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Palestine; State of');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Ireland');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Falkland Islands');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Turkey');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Zimbabwe');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Vanuatu');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Myanmar');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Mali');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Vanuatu');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Greenland');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('El Salvador');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Luxembourg');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Angola');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Albania');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Colombia');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Sweden');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Senegal');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Afghanistan');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Sweden');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Burundi');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Oman');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Belgium');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Korea; North');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Madagascar');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Curaçao');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Germany');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Ghana');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('New Zealand');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Burkina Faso');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Tokelau');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Macedonia');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Guyana');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Laos');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Saudi Arabia');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Barbados');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Turkey');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Finland');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Virgin Islands; United States');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Wallis and Futuna');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Saint Kitts and Nevis');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Aruba');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Cambodia');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Brunei');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Nicaragua');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Qatar');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Tajikistan');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Sint Maarten');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Tanzania');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Dominican Republic');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Qatar');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Madagascar');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Haiti');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Sint Maarten');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Western Sahara');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Suriname');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Ethiopia');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Liechtenstein');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Turkmenistan');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Virgin Islands; United States');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Palestine; State of');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Kuwait');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('New Caledonia');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Congo; the Democratic Republic of the');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Germany');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Paraguay');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Azerbaijan');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Antigua and Barbuda');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Suriname');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('American Samoa');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Thailand');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Botswana');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Burundi');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Bulgaria');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Christmas Island');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Belize');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Taiwan');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('South Georgia and The South Sandwich Islands');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Togo');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Moldova');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Ukraine');
INSERT INTO  `bdd_airguitare`.`pays` (`nom`) VALUES ('Saint Martin');

INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("381177","Lakeshore",36);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("18352","Kedzierzyn-Kozle",44);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("5753YG","Merdorp",80);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("Y0G 1G3","Sissa",76);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("8656","Avise",27);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("03506","Whitchurch-Stouffville",3);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("ZK0 0PO","Armadale",44);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("10011","Borghetto di Vara",68);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("35563","Nizip",2);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("11618","Cape Breton Island",67);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("6238VS","Kailua",26);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("36530","Scheggino",3);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("40411","Ambresin",36);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("48649","Mandurah",31);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("574646","Berlin",45);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("72878","Attert",92);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("464306","Ancaster Town",16);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("QI8 9GX","Kawawachikamach",44);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("168965","Sneek",44);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("6854","Glabais",64);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("59140-445","Mata de Plátano",97);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("7426","Daman",82);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("5029","Maria",96);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("2967","Sesto al Reghena",93);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("O00 2HS","Gloucester",95);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("774809","Loupoigne",84);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("59875","Cerreto di Spoleto",97);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("7035RU","Rotorua",16);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("689080","Bari",65);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("TV5 6PV","Leamington",68);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("19513","Villanovafranca",49);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("17867","Delhi",16);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("9109","Chapra",30);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("38121","Roux-Miroir",14);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("976137","Calder",65);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("5614","Merzig",47);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("541669","Philadelphia",55);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("10316","Hemel Hempstead",51);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("7999","Caldarola",16);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("E7T 0E3","Aguacaliente (San Francisco)",69);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("42979","Buzenol",72);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("3500","Troyes",22);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("B6Y 7P8","Stony Plain",61);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("629127","Montpellier",93);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("G0J 7P9","San Francisco",82);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("50430","Siverek",36);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("35818","Bossuit",54);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("008975","Memphis",75);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("422193","Glimes",93);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("19397-193","Pembroke",18);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("671215","Workington",19);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("15413","Recife",81);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("0241","Gorzów Wielkopolski",73);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("5214","Casnate con Bernate",14);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("31500","Mercedes",90);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("9390VD","Serskamp",53);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("4683","St. Catharines",17);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("8703","Kirikhan",52);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("50403","Bastia",41);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("08214","Siquirres",43);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("62339","Virginia Beach",3);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("4340","Itajaí",92);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("37132","Port Lincoln",78);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("40280","Gambolò",31);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("8562","Groot-Bijgaarden",76);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("3369","Mesa",28);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("66579","Aulnay-sous-Bois",28);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("3479","Outrijve",48);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("4279","Solihull",42);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("188242","Fort Laird",25);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("7471","Buzet",73);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("27899","Pettineo",21);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("84167","Dilsen-Stokkem",75);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("47174","Phoenix",66);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("8450","Torgnon",75);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("80939-693","Bahawalpur",76);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("1099PI","Fermont",71);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("87932","Roux",73);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("1761","Parral",25);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("71309","St. Catharines",58);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("8370","Rockingham",81);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("4172PL","Pugwash",29);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("52026","Toowoomba",68);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("09153","Richmond",90);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("2740","Leganés",66);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("349331","Monte Patria",18);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("417719","Coevorden",20);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("79056","Drayton Valley",87);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("08-867","Codognè",64);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("49612","Adelaide",63);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("10712","Vernole",66);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("476652","Hull",97);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("800505","Casacalenda",35);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("21518","Wick",18);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("75210","Cuxhaven",93);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("85789","Duluth",84);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("30217","Napier",75);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("6384","Waidhofen an der Ybbs",55);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("06770","Yorkton",31);
INSERT INTO  `bdd_airguitare`.`ville` (`codePostal`,`nom`,`pays_id`) VALUES ("31617","Santa Cesarea Terme",85);

INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("vitae, sodales at,",1,"Appartement 957-6848 Odio Impasse",10);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Nulla",10,"CP 779, 8077 Morbi Ave",51);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("tortor, dictum eu, placerat eget, venenatis",4,"CP 630, 6379 Elit. Rue",4);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("mi tempor lorem, eget mollis lectus",6,"CP 738, 7413 Felis. Impasse",85);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("mi eleifend egestas. Sed pharetra, felis eget",15,"Appartement 256-271 Ultrices Impasse",65);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem",5,"Appartement 497-3720 Phasellus Avenue",54);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis",24,"Appartement 624-412 Imperdiet Rd.",20);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("vitae",18,"3427 Ornare Av.",5);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("torquent per conubia",6,"Appartement 460-7405 Consequat Rd.",23);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("sagittis. Nullam vitae diam. Proin dolor. Nulla",2,"3915 Dignissim Ave",57);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("tristique senectus et netus et malesuada fames ac turpis",12,"638-9993 Elit. Rue",85);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("ornare, libero at auctor",13,"3940 Aliquam Chemin",50);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("rutrum urna, nec luctus felis purus ac",5,"1490 Posuere Rue",47);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat",21,"175-7231 Et, Av.",83);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("a, malesuada id,",15,"CP 698, 5929 Ipsum Avenue",22);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi",11,"CP 503, 2996 Vulputate Avenue",67);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("sagittis. Duis gravida. Praesent eu nulla at sem",10,"251-1395 Dis Rd.",80);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("auctor ullamcorper, nisl arcu iaculis enim,",17,"Appartement 312-5417 At, Route",55);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce",2,"5328 Nec Ave",26);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("cursus non, egestas a, dui.",1,"Appartement 833-444 Non, Chemin",36);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("pede nec ante blandit viverra. Donec tempus,",20,"4763 Bibendum. Rue",26);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("at pretium aliquet, metus urna",17,"360 Ante Rd.",94);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("ipsum. Suspendisse sagittis. Nullam vitae diam. Proin",19,"CP 831, 5698 Pede. Avenue",69);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi",14,"4111 Gravida Route",88);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("sit amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet",22,"CP 118, 8410 Mi. Rue",67);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("commodo at, libero. Morbi accumsan laoreet ipsum.",12,"7171 A, Rd.",24);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Donec feugiat metus sit amet ante. Vivamus non lorem vitae",22,"573-1222 Tellus Avenue",100);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("vehicula",10,"263-6094 Aliquam Route",34);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Phasellus at augue id",7,"CP 585, 3472 Suspendisse Av.",20);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Nullam suscipit,",10,"875-3727 Massa Impasse",68);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("sit amet,",19,"8700 Montes, Chemin",84);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("dolor. Donec fringilla. Donec feugiat",17,"3878 Malesuada Chemin",23);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("feugiat metus sit amet ante. Vivamus non lorem vitae odio",24,"151-7849 Pellentesque Rd.",5);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("ut odio vel est tempor bibendum.",2,"158-925 Ut Av.",100);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("tempor bibendum. Donec",6,"271-498 Eu, Ave",73);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("elit, pharetra ut, pharetra sed, hendrerit a, arcu.",5,"4098 Enim Route",47);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla.",17,"Appartement 412-6063 Vel Route",55);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("turpis egestas.",1,"484-2615 Magna. Route",84);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("dolor elit, pellentesque a, facilisis non,",7,"CP 160, 6868 Pede Rue",35);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo",4,"Appartement 691-5943 Porttitor Route",4);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Aenean massa. Integer vitae nibh. Donec est mauris, rhoncus id,",7,"Appartement 675-2594 Metus Impasse",69);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("nulla at",23,"Appartement 573-4871 Adipiscing. Rue",55);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut,",13,"631-2038 Enim. Route",65);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Integer mollis. Integer",12,"440-6834 Mauris Impasse",84);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("eu neque pellentesque",13,"810-2040 Ipsum Route",26);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("aliquet. Proin velit.",1,"CP 280, 5518 At Route",12);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("neque et",8,"722-6896 Ut Avenue",45);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("habitant morbi tristique senectus et",13,"400-2529 Mauris. Av.",1);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Proin dolor. Nulla semper tellus",11,"829-4523 Augue Impasse",32);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("tincidunt, neque vitae",16,"139-2499 Sagittis Av.",98);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("rhoncus. Donec",12,"CP 603, 2838 Nec Ave",68);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("dis parturient montes, nascetur ridiculus mus. Proin",22,"Appartement 828-1404 Amet Ave",26);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("fringilla ornare placerat,",10,"CP 882, 6404 Nullam Chemin",62);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Morbi vehicula. Pellentesque tincidunt",18,"Appartement 125-7248 Eu Rue",48);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("netus et",17,"Appartement 575-823 Fringilla Rue",94);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("risus. Donec",17,"7783 Cras Chemin",49);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("ipsum nunc",2,"Appartement 266-2188 Tellus Avenue",81);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("metus urna convallis erat, eget",23,"CP 537, 312 Lectus Route",25);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id",20,"CP 981, 5363 Metus. Route",41);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Nam ac nulla. In tincidunt congue turpis.",3,"6970 Tincidunt Rue",22);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("et netus",9,"829 Dictum Impasse",75);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("facilisis facilisis, magna tellus faucibus",18,"Appartement 246-8854 Aenean Av.",51);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("sem semper erat, in consectetuer ipsum nunc",17,"Appartement 893-3877 Gravida Chemin",58);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("interdum ligula eu enim. Etiam imperdiet dictum",20,"110-3530 Dictum Route",3);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("eget varius ultrices,",8,"CP 945, 7256 A Rd.",48);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("et, rutrum non, hendrerit id,",3,"685-9058 Nulla Rue",46);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("eu augue porttitor interdum. Sed auctor odio",9,"CP 392, 1820 Turpis Rd.",90);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("taciti sociosqu ad litora torquent per conubia nostra, per",6,"Appartement 950-9260 Tincidunt Impasse",99);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("tellus sem mollis",20,"Appartement 504-2264 Felis Impasse",9);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("natoque penatibus et magnis dis",17,"CP 614, 7908 Dictum Route",40);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("augue eu tellus. Phasellus elit",11,"Appartement 264-7380 Vulputate Rd.",81);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("consectetuer euismod est",4,"Appartement 782-5257 Neque Ave",32);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Suspendisse",10,"389-4311 Risus, Rd.",95);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("urna, nec",17,"Appartement 314-8805 Blandit. Ave",15);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("eu enim.",3,"Appartement 955-750 Aliquam Chemin",61);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("lectus quis massa. Mauris vestibulum, neque sed",23,"3398 Ad Avenue",32);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec",21,"Appartement 902-2442 Nonummy. Impasse",61);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("auctor non, feugiat nec, diam. Duis mi enim, condimentum",10,"Appartement 724-6709 Vitae Impasse",40);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("ac mattis semper, dui lectus rutrum urna, nec",11,"347-2585 Vitae Chemin",33);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("velit. Cras lorem lorem, luctus ut, pellentesque eget,",24,"CP 123, 1049 Tristique Route",63);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa.",20,"CP 280, 3024 Turpis. Rd.",10);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("odio, auctor vitae, aliquet nec, imperdiet nec, leo.",20,"9879 Odio. Rue",37);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("mi tempor lorem, eget",23,"131-7736 Tincidunt, Route",45);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Suspendisse aliquet, sem ut cursus luctus, ipsum",2,"Appartement 832-4107 Ut Rue",68);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("sed pede nec ante blandit viverra. Donec",24,"Appartement 678-4858 Quisque Rue",87);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("nascetur ridiculus mus.",19,"7488 Metus. Rd.",16);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis",6,"Appartement 643-2430 Pede, Avenue",57);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("egestas a, dui. Cras pellentesque.",9,"481-5841 Ridiculus Avenue",15);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Morbi neque tellus, imperdiet non,",20,"Appartement 268-3891 Id Rue",97);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("mauris.",18,"5102 Gravida Avenue",96);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("semper rutrum. Fusce dolor quam, elementum at, egestas a,",24,"790-4558 Vel, Av.",48);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("netus et malesuada fames ac turpis",2,"CP 846, 9138 Risus. Avenue",90);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis",7,"365-9204 Ante Impasse",41);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("non quam. Pellentesque habitant morbi tristique senectus et netus et",5,"6497 Augue, Avenue",34);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("est tempor bibendum. Donec felis orci, adipiscing",9,"Appartement 846-1517 Mauris Route",26);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("ac orci. Ut semper pretium neque. Morbi",18,"6067 Turpis Av.",30);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Ut tincidunt vehicula risus. Nulla eget metus",10,"711 Metus. Ave",56);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("sed, facilisis vitae, orci. Phasellus dapibus",23,"CP 703, 427 A, Route",1);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("congue a, aliquet vel, vulputate eu, odio. Phasellus at augue",6,"CP 269, 4121 Justo Ave",7);
INSERT INTO  `bdd_airguitare`.`adresse` (`complement`,`numero`,`rue`,`ville_id`) VALUES ("Integer tincidunt aliquam",21,"Appartement 696-4758 Dolor Avenue",36);

INSERT INTO  `bdd_airguitare`.`articleblog` (`description`,`intitule`) VALUES ("Lorem ipsum dolor sit amet, consectetuer","Fusce fermentum fermentum arcu.");
INSERT INTO  `bdd_airguitare`.`articleblog` (`description`,`intitule`) VALUES ("Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at","litora torquent per conubia");
INSERT INTO  `bdd_airguitare`.`articleblog` (`description`,`intitule`) VALUES ("Lorem ipsum dolor","Ut nec urna et");
INSERT INTO  `bdd_airguitare`.`articleblog` (`description`,`intitule`) VALUES ("Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida","consectetuer adipiscing elit. Aliquam");
INSERT INTO  `bdd_airguitare`.`articleblog` (`description`,`intitule`) VALUES ("Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et arcu","cursus. Integer mollis. Integer");
INSERT INTO  `bdd_airguitare`.`articleblog` (`description`,`intitule`) VALUES ("Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna","in felis. Nulla tempor");

INSERT INTO  `bdd_airguitare`.`typeproduit` (`intitule`) VALUES ("guitare");
INSERT INTO  `bdd_airguitare`.`typeproduit` (`intitule`) VALUES ("housses et étui");
INSERT INTO  `bdd_airguitare`.`typeproduit` (`intitule`) VALUES ("pupitres");

INSERT INTO  `bdd_airguitare`.`specialisationproduit` (`intitule`,`typeProduit_id`) VALUES ("guitares électriques",1);
INSERT INTO  `bdd_airguitare`.`specialisationproduit` (`intitule`,`typeProduit_id`) VALUES ("guitares classiques",1);

INSERT INTO  `bdd_airguitare`.`themearticle` (`intitule`) VALUES ("compétition");
INSERT INTO  `bdd_airguitare`.`themearticle` (`intitule`) VALUES ("nouveaux produits");

INSERT INTO  `bdd_airguitare`.`themearticle_articleblog` (`themes_id`, `articles_id`) VALUES (1,1);
INSERT INTO  `bdd_airguitare`.`themearticle_articleblog` (`themes_id`, `articles_id`) VALUES (1,2);
INSERT INTO  `bdd_airguitare`.`themearticle_articleblog` (`themes_id`, `articles_id`) VALUES (1,3);
INSERT INTO  `bdd_airguitare`.`themearticle_articleblog` (`themes_id`, `articles_id`) VALUES (2,4);
INSERT INTO  `bdd_airguitare`.`themearticle_articleblog` (`themes_id`, `articles_id`) VALUES (2,5);
INSERT INTO  `bdd_airguitare`.`themearticle_articleblog` (`themes_id`, `articles_id`) VALUES (2,6);

INSERT INTO  `bdd_airguitare`.`personne` (`adresseMail`,`dateNaissance`,`nom`,`password`,`prenom`,`statut`,`telephone`) VALUES ("Sed@pedeet.com","1986/06/08","Hartman","469701056","Thaddeus","Administrateur","03 12 73 60 31");
INSERT INTO  `bdd_airguitare`.`personne` (`adresseMail`,`dateNaissance`,`nom`,`password`,`prenom`,`statut`,`telephone`) VALUES ("natoque.penatibus@ac.net","1993/08/10","Gates","675033500","Beck","Administrateur","07 94 28 23 22");
INSERT INTO  `bdd_airguitare`.`personne` (`adresseMail`,`dateNaissance`,`nom`,`password`,`prenom`,`statut`,`telephone`) VALUES ("Sed.nulla@risusatfringilla.ca","1992/04/05","Knapp","801274259","Zeus","Administrateur","05 93 30 14 70");
INSERT INTO  `bdd_airguitare`.`personne` (`adresseMail`,`dateNaissance`,`nom`,`password`,`prenom`,`statut`,`telephone`) VALUES ("habitant@felis.org","1992/01/19","Stephens","881407738","Wylie","Client","06 49 25 34 09");
INSERT INTO  `bdd_airguitare`.`personne` (`adresseMail`,`dateNaissance`,`nom`,`password`,`prenom`,`statut`,`telephone`) VALUES ("Proin.sed@mauris.edu","1992/08/25","Solomon","770753531","Amal","Client","08 72 67 99 54");
INSERT INTO  `bdd_airguitare`.`personne` (`adresseMail`,`dateNaissance`,`nom`,`password`,`prenom`,`statut`,`telephone`) VALUES ("pede@bibendum.com","1994/04/10","Frank","067113449","Linus","Client","08 41 37 95 05");
INSERT INTO  `bdd_airguitare`.`personne` (`adresseMail`,`dateNaissance`,`nom`,`password`,`prenom`,`statut`,`telephone`) VALUES ("Quisque@Inmipede.net","1998/03/24","Meadows","818128779","Lucas","Client","03 40 95 85 10");
INSERT INTO  `bdd_airguitare`.`personne` (`adresseMail`,`dateNaissance`,`nom`,`password`,`prenom`,`statut`,`telephone`) VALUES ("ac@risusDonec.org","1996/12/11","Henry","732230271","Thomas","Client","08 25 15 49 11");
INSERT INTO  `bdd_airguitare`.`personne` (`adresseMail`,`dateNaissance`,`nom`,`password`,`prenom`,`statut`,`telephone`) VALUES ("Duis@pedenonummy.co.uk","1992/12/10","English","709532881","Kasimir","Client","03 46 65 75 52");
INSERT INTO  `bdd_airguitare`.`personne` (`adresseMail`,`dateNaissance`,`nom`,`password`,`prenom`,`statut`,`telephone`) VALUES ("tortor@urna.net","1984/10/22","Thomas","173050709","Conan","Client","08 55 81 42 97");
INSERT INTO  `bdd_airguitare`.`personne` (`adresseMail`,`dateNaissance`,`nom`,`password`,`prenom`,`statut`,`telephone`) VALUES ("Nam@lacusCrasinterdum.com","1980/06/22","Moses","758847875","Leo","Client","08 33 34 05 26");

INSERT INTO  `bdd_airguitare`.`personne_adresse` (`personnes_id`,`adresses_id`) VALUES (1,1);
INSERT INTO  `bdd_airguitare`.`personne_adresse` (`personnes_id`,`adresses_id`) VALUES (2,1);
INSERT INTO  `bdd_airguitare`.`personne_adresse` (`personnes_id`,`adresses_id`) VALUES (3,2);
INSERT INTO  `bdd_airguitare`.`personne_adresse` (`personnes_id`,`adresses_id`) VALUES (4,3);
INSERT INTO  `bdd_airguitare`.`personne_adresse` (`personnes_id`,`adresses_id`) VALUES (5,4);
INSERT INTO  `bdd_airguitare`.`personne_adresse` (`personnes_id`,`adresses_id`) VALUES (6,4);
INSERT INTO  `bdd_airguitare`.`personne_adresse` (`personnes_id`,`adresses_id`) VALUES (7,5);
INSERT INTO  `bdd_airguitare`.`personne_adresse` (`personnes_id`,`adresses_id`) VALUES (8,6);
INSERT INTO  `bdd_airguitare`.`personne_adresse` (`personnes_id`,`adresses_id`) VALUES (9,7);
INSERT INTO  `bdd_airguitare`.`personne_adresse` (`personnes_id`,`adresses_id`) VALUES (10,8);
INSERT INTO  `bdd_airguitare`.`personne_adresse` (`personnes_id`,`adresses_id`) VALUES (11,9);

INSERT INTO  `bdd_airguitare`.`marque` (`intitule`,`logo`) VALUES ("Yamaha",null);
INSERT INTO  `bdd_airguitare`.`marque` (`intitule`,`logo`) VALUES ("Bird",null);
INSERT INTO  `bdd_airguitare`.`marque` (`intitule`,`logo`) VALUES ("Cuenca",null);
INSERT INTO  `bdd_airguitare`.`marque` (`intitule`,`logo`) VALUES ("Esteve",null);